# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'web2020@52.170.207.148'
    contents: |
      setup.sh
      requirements.txt
      hello.py
    targetFolder: '/home/web2020'
    readyTimeout: '20000'





steps:
- script: bash setup.sh
  displayName: 'setup env.'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

